site_name: Devops wiki
site_url: https://9159340.github.io/devops/

theme:
  name: material
  language: ru
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Переключить на тёмную тему
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Переключить на светлую тему

nav:
  - Главная: index.md

  - Linux:
      - CRON: linux/cron.md
      - SSH: linux/ssh.md
      - Systemd: linux/systemd.md
      
  - Docker:
      - Docker: docker/index.md
      - Compose: docker/compose.md

  - Git:
      - Основы: git/index.md
      - Worktree: git/worktree.md

  - Kafka:
      - Kafka: kafka/index.md
